# Unbounded arrays of built-in types
bool[] boolean_unbounded_array
char[] char_unbounded_array
byte[] byte_unbounded_array
int8[] int8_unbounded_array
uint8[] uint8_unbounded_array
int16[] int16_unbounded_array
uint16[] uint16_unbounded_array
int32[] int32_unbounded_array
uint32[] uint32_unbounded_array
int64[] int64_unbounded_array
uint64[] uint64_unbounded_array
float32[] float32_unbounded_array
float64[] float64_unbounded_array
string[] string_unbounded_array
string<=5[] bounded_string_unbounded_array

# Bounded arrays of built-in types
bool[<=2] boolean_bounded_array
char[<=2] char_bounded_array
byte[<=2] byte_bounded_array
int8[<=2] int8_bounded_array
uint8[<=2] uint8_bounded_array
int16[<=2] int16_bounded_array
uint16[<=2] uint16_bounded_array
int32[<=2] int32_bounded_array
uint32[<=2] uint32_bounded_array
int64[<=2] int64_bounded_array
uint64[<=2] uint64_bounded_array
float32[<=2] float32_bounded_array
float64[<=2] float64_bounded_array
string[<=2] string_bounded_array
string<=5[<=2] bounded_string_bounded_array       