module rosidl_generator_py {
    module msg {
        struct BuiltinTypesIdl {
            // Built-in types
            boolean boolean_value;
            char char_value;
            octet octet_value;
            short short_value;
            unsigned short unsigned_short_value;
            long long_value;
            unsigned long unsigned_long_value;
            long long long_long_value;
            unsigned long long unsigned_long_long_value;
            float float_value;
            double double_value;
            int8 int8_value;
            uint8 uint8_value;
            int16 int16_value;
            uint16 uint16_value;
            int32 int32_value;
            uint32 uint32_value;
            int64 int64_value;
            uint64 uint64_value;
            string string_value;
            string<5> bounded_string_value;

            // Arrays of built-in types
            boolean boolean_array[2];
            char char_array[2];
            octet octet_array[2];
            short short_array[2];
            unsigned short unsigned_short_array[2];
            long long_array[2];
            unsigned long unsigned_long_array[2];
            long long long_long_array[2];
            unsigned long long unsigned_long_long_array[2];
            float float_array[2];
            double double_array[2];
            int8 int8_array[2];
            uint8 uint8_array[2];
            int16 int16_array[2];
            uint16 uint16_array[2];
            int32 int32_array[2];
            uint32 uint32_array[2];
            int64 int64_array[2];
            uint64 uint64_array[2];
            string string_array[2];
            string<5> bounded_string_array[2];
        };
    };
};