# Built-in types
bool boolean_value
char char_value
byte byte_value
int8 int8_value
uint8 uint8_value
int16 int16_value
uint16 uint16_value
int32 int32_value
uint32 uint32_value
int64 int64_value
uint64 uint64_value
float32 float32_value
float64 float64_value
string string_value
string<=5 bounded_string_value

# Static arrays of built-in types
bool[2] boolean_array
char[2] char_array
byte[2] byte_array
int8[2] int8_array
uint8[2] uint8_array
int16[2] int16_array
uint16[2] uint16_array
int32[2] int32_array
uint32[2] uint32_array
int64[2] int64_array
uint64[2] uint64_array
float32[2] float32_array
float64[2] float64_array
string[2] string_array
string<=5[2] bounded_string_array